# Generated by Django 5.1.10 on 2025-08-15 16:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('players', '0002_player_birth_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='player',
            name='clearances_blocks_interceptions',
            field=models.IntegerField(null=True),
        ),
        migrations.AddField(
            model_name='player',
            name='defensive_contribution',
            field=models.IntegerField(null=True),
        ),
        migrations.AddField(
            model_name='player',
            name='defensive_contribution_per_90',
            field=models.IntegerField(null=True),
        ),
        migrations.AddField(
            model_name='player',
            name='recoveries',
            field=models.IntegerField(null=True),
        ),
        migrations.AddField(
            model_name='player',
            name='tackles',
            field=models.IntegerField(null=True),
        ),
    ]
