# Generated by Django 5.1.10 on 2025-08-26 14:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('players', '0003_player_clearances_blocks_interceptions_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='player',
            name='mng_clean_sheets',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='player',
            name='mng_draw',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='player',
            name='mng_goals_scored',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='player',
            name='mng_loss',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='player',
            name='mng_underdog_draw',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='player',
            name='mng_underdog_win',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='player',
            name='mng_win',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
