# Generated by Django 5.1.10 on 2025-08-26 14:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('players', '0005_alter_playerhistory_mng_clean_sheets_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='playerhistory',
            name='clearances_blocks_interceptions',
            field=models.IntegerField(null=True),
        ),
        migrations.AddField(
            model_name='playerhistory',
            name='defensive_contribution',
            field=models.IntegerField(null=True),
        ),
        migrations.AddField(
            model_name='playerhistory',
            name='recoveries',
            field=models.IntegerField(null=True),
        ),
        migrations.AddField(
            model_name='playerhistory',
            name='tackles',
            field=models.IntegerField(null=True),
        ),
    ]
