# Generated by Django 6.0 on 2026-01-12 19:42

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('teams', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Event',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('name', models.CharField(blank=True, max_length=20)),
                ('deadline_time', models.DateTimeField(null=True)),
                ('release_time', models.DateTimeField(blank=True, null=True)),
                ('average_entry_score', models.IntegerField(null=True)),
                ('finished', models.BooleanField(default=False)),
                ('data_checked', models.BooleanField(default=False)),
                ('highest_scoring_entry', models.IntegerField(blank=True, null=True)),
                ('deadline_time_epoch', models.IntegerField(null=True)),
                ('deadline_time_game_offset', models.IntegerField(null=True)),
                ('highest_score', models.IntegerField(blank=True, null=True)),
                ('is_previous', models.BooleanField(default=False)),
                ('is_current', models.BooleanField(default=False)),
                ('is_next', models.BooleanField(default=False)),
                ('cup_leagues_created', models.BooleanField(default=False)),
                ('h2h_ko_matches_created', models.BooleanField(default=False)),
                ('ranked_count', models.IntegerField(null=True)),
                ('chip_plays', models.JSONField(blank=True, default=list)),
                ('most_selected', models.IntegerField(blank=True, null=True)),
                ('most_transferred_in', models.IntegerField(blank=True, null=True)),
                ('top_element', models.IntegerField(blank=True, null=True)),
                ('top_element_info', models.JSONField(blank=True, null=True)),
                ('transfers_made', models.IntegerField(null=True)),
                ('most_captained', models.IntegerField(blank=True, null=True)),
                ('most_vice_captained', models.IntegerField(blank=True, null=True)),
                ('can_enter', models.BooleanField(default=False)),
                ('can_manage', models.BooleanField(default=False)),
                ('released', models.BooleanField(default=False)),
                ('last_updated', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='EventStatus',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('bonus_added', models.BooleanField()),
                ('date', models.DateField()),
                ('event', models.IntegerField(null=True)),
                ('points', models.CharField(blank=True, max_length=1)),
                ('last_updated', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='Fixture',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('code', models.IntegerField(null=True)),
                ('event', models.IntegerField(blank=True, null=True)),
                ('finished', models.BooleanField(null=True)),
                ('finished_provisional', models.BooleanField(null=True)),
                ('kickoff_time', models.DateTimeField(blank=True, null=True)),
                ('minutes', models.IntegerField(null=True)),
                ('provisional_start_time', models.BooleanField(null=True)),
                ('started', models.BooleanField(blank=True, null=True)),
                ('team_a', models.IntegerField(null=True)),
                ('team_a_score', models.IntegerField(blank=True, null=True)),
                ('team_h', models.IntegerField(null=True)),
                ('team_h_score', models.IntegerField(blank=True, null=True)),
                ('stats', models.TextField(blank=True)),
                ('team_h_difficulty', models.IntegerField(null=True)),
                ('team_a_difficulty', models.IntegerField(null=True)),
                ('pulse_id', models.IntegerField(null=True)),
                ('last_updated', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='FixtureStats',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('identifier', models.CharField(choices=[('goals_scored', 'Goals Scored'), ('assists', 'Assists'), ('own_goals', 'Own Goals'), ('penalties_saved', 'Penalties Saved'), ('penalties_missed', 'Penalties Missed'), ('yellow_cards', 'Yellow Cards'), ('red_cards', 'Red Cards'), ('saves', 'Saves'), ('bonus', 'Bonus'), ('bps', 'Bps'), ('mng_underdog_win', 'Manager Underdog Win'), ('mng_underdog_draw', 'Manager Underdog Draw')], max_length=50)),
                ('value', models.IntegerField()),
                ('home_or_away', models.CharField(choices=[('home', 'Home'), ('away', 'Away')], max_length=4)),
                ('last_updated', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='LastUpdated',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fpl_data', models.DateTimeField(null=True)),
                ('live_data', models.DateTimeField(null=True)),
                ('fixture_data', models.DateTimeField(null=True)),
                ('prediction_data', models.DateTimeField(null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Phase',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=10)),
                ('start_event', models.IntegerField(null=True)),
                ('stop_event', models.IntegerField(null=True)),
                ('highest_score', models.IntegerField(blank=True, null=True)),
                ('last_updated', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='Season',
            fields=[
                ('season', models.IntegerField(primary_key=True, serialize=False)),
                ('last_updated', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='EventOverride',
            fields=[
                ('gameweek', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='common.event')),
                ('pick_multiplier', models.IntegerField(blank=True, null=True)),
                ('rules', models.JSONField(blank=True, default=dict)),
                ('scoring', models.JSONField(blank=True, default=dict)),
                ('last_updated', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.AddConstraint(
            model_name='event',
            constraint=models.UniqueConstraint(fields=('id',), name='unique_event'),
        ),
        migrations.AddField(
            model_name='eventstatus',
            name='gameweek',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='common.event'),
        ),
        migrations.AddField(
            model_name='fixture',
            name='team_away',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='fix_away_team', to='teams.team'),
        ),
        migrations.AddField(
            model_name='fixture',
            name='team_home',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='fix_home_team', to='teams.team'),
        ),
        migrations.AddField(
            model_name='fixturestats',
            name='fixture',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='fixture_stats', to='common.fixture'),
        ),
    ]
