# Generated by Django 6.0 on 2026-01-12 19:42

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('common', '0001_initial'),
        ('players', '0001_initial'),
        ('teams', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='fixturestats',
            name='player',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='players.player'),
        ),
        migrations.AddField(
            model_name='fixturestats',
            name='team',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='teams.team'),
        ),
        migrations.AddConstraint(
            model_name='phase',
            constraint=models.UniqueConstraint(fields=('id', 'name'), name='unique_phase'),
        ),
        migrations.AddConstraint(
            model_name='season',
            constraint=models.UniqueConstraint(fields=('season',), name='unique_season'),
        ),
        migrations.AddField(
            model_name='eventoverride',
            name='element_types',
            field=models.ManyToManyField(to='players.elementtype'),
        ),
        migrations.AddConstraint(
            model_name='eventstatus',
            constraint=models.UniqueConstraint(fields=('event', 'date'), name='unique_event_status'),
        ),
        migrations.AddConstraint(
            model_name='fixture',
            constraint=models.UniqueConstraint(fields=('id', 'team_h', 'team_a'), name='unique_fixture'),
        ),
        migrations.AddConstraint(
            model_name='fixturestats',
            constraint=models.UniqueConstraint(fields=('fixture', 'identifier', 'player', 'team'), name='unique_fixture_stat'),
        ),
        migrations.AddConstraint(
            model_name='eventoverride',
            constraint=models.UniqueConstraint(fields=('gameweek',), name='unique_event_override'),
        ),
    ]
