# Generated by Django 6.0 on 2026-01-17 18:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('common', '0002_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='fixturestats',
            name='identifier',
            field=models.CharField(choices=[('goals_scored', 'Goals Scored'), ('assists', 'Assists'), ('own_goals', 'Own Goals'), ('penalties_saved', 'Penalties Saved'), ('penalties_missed', 'Penalties Missed'), ('yellow_cards', 'Yellow Cards'), ('red_cards', 'Red Cards'), ('saves', 'Saves'), ('bonus', 'Bonus'), ('bps', 'Bps'), ('defensive_contribution', 'Defensive Contribution'), ('mng_underdog_win', 'Manager Underdog Win'), ('mng_underdog_draw', 'Manager Underdog Draw')], max_length=50),
        ),
    ]
