# Generated by Django 6.0 on 2026-01-17 18:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('common', '0003_alter_fixturestats_identifier'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='event',
            name='chip_plays',
        ),
    ]
