# Generated by Django 6.0 on 2026-01-17 18:43

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('common', '0004_remove_event_chip_plays'),
    ]

    operations = [
        migrations.CreateModel(
            name='EventChipPlay',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('chip_name', models.CharField(choices=[('bboost', 'Bench Boost'), ('freehit', 'Free Hit'), ('wildcard', 'Wildcard'), ('3xc', 'Triple Captain')], max_length=20)),
                ('num_played', models.IntegerField()),
                ('event', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='chip_plays', to='common.event')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
