# Generated by Django 6.0 on 2026-01-12 19:42

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Tweet',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('gameweek', models.IntegerField(null=True)),
                ('predictions_media_id', models.IntegerField(null=True)),
                ('actuals_media_id', models.IntegerField(null=True)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
            ],
            options={
                'constraints': [models.UniqueConstraint(fields=('id',), name='unique_tweet')],
            },
        ),
    ]
