# Generated by Django 5.1.5 on 2025-02-02 11:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('manager', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='classicleaguelivestandings',
            name='mng_clean_sheets',
            field=models.IntegerField(null=True),
        ),
        migrations.AddField(
            model_name='classicleaguelivestandings',
            name='mng_draw',
            field=models.IntegerField(null=True),
        ),
        migrations.AddField(
            model_name='classicleaguelivestandings',
            name='mng_goals_scored',
            field=models.IntegerField(null=True),
        ),
        migrations.AddField(
            model_name='classicleaguelivestandings',
            name='mng_loss',
            field=models.IntegerField(null=True),
        ),
        migrations.AddField(
            model_name='classicleaguelivestandings',
            name='mng_underdog_draw',
            field=models.IntegerField(null=True),
        ),
        migrations.AddField(
            model_name='classicleaguelivestandings',
            name='mng_underdog_win',
            field=models.IntegerField(null=True),
        ),
        migrations.AddField(
            model_name='classicleaguelivestandings',
            name='mng_win',
            field=models.IntegerField(null=True),
        ),
    ]
