[DEFAULT]
# FPL APU properties
base_url = https://fantasy.premierleague.com/api/
bootstrap_static_url = bootstrap-static/
fixtures_url = fixtures/
player_url = element-summary/{}/
manager_base_url = entry/{}/
manager_picks_url = event/{}/picks/
classic_league_url = leagues-classic/{}/standings
event_standings_url = entry/{}/history/
live_standings_url = event/{}/live
event_status_url = event-status/

# FDR properties
fdr_easiest=1
fdr_hardest=5

# Reload cache (minutes)
reload_full_cache_time = 120
reload_live_cache_time = 1
reload_fixture_cache_time = 1
reload_manager_cache_time = 60
reload_data = True
reload_fixtures = True
retry_attempts = 10
request_timeout = 5
request_delay = 2

# Message timeout
message_short_timeout = 500
message_timeout = 5000

# ML Player properties
ml_enabled = True
minutes_played = 60
rolling_average = 4

# Number of games
number_of_gameweeks = 38

# Page size
page_size = 12
league_page_size = 50
progression_players_to_show = 15

# Team previous position
team_previous_position_file = team_position_2024.json

# Fonts, images and hastags for predictions
text_font = static/fonts/SeafordRg.ttf
header_font = static/fonts/SeafordBold.ttf
watermark = static/images/watermark.png
predictions_images = predictions/images
hashtags = #fpl #fplpredictions #fplai #ai #ml

# Default manager ids
manager_ids =
debug_mode = True

# Denied messages
league_access_denied = Public league won't be loaded. There is too much data, and you won't find yourself anyway <i class="bi bi-emoji-wink"></i>
