"""
Django settings for fpl project.

Generated by 'django-admin startproject' using Django 3.2.9.

For more information on this file, see
https://docs.djangoproject.com/en/3.2/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/3.2/ref/settings/
"""
import os
import sys
from logging.handlers import TimedRotatingFileHandler
from pathlib import Path

import django
from dotenv import load_dotenv

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent

# Load environment variables from the .env file
dotenv_path = os.path.join(BASE_DIR, '.env')
load_dotenv(dotenv_path)

# Get the application version from environment variable
APP_VERSION = os.getenv('APP_VERSION', 'Unknown version')
print(f"Starting application with Application version: {APP_VERSION}")
print(f"Starting application with Python version: {sys.version}")
print(f"Starting application with Django version: {django.get_version()}")

# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/3.2/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = 'django-insecure-t=%1!2q4u)%xh-xxhao48@1rh@768g(*kj!u=is(qeesmq!s8s'

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = True

ALLOWED_HOSTS = ['*']


# Application definition

INSTALLED_APPS = [
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    'django_extensions',
    "rest_framework",
    "django_filters",
    "corsheaders",
    "drf_spectacular",
    'widget_tweaks',
    'bootstrap_modal_forms',
    'fpl',
    'teams',
    'players',
    'common',
    'manager',
    'penalties',
    'settings',
    'tweets',
]

MIDDLEWARE = [
    'corsheaders.middleware.CorsMiddleware',
    'django.middleware.security.SecurityMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
    'fpl.middleware.AccessMiddleware',
]

CORS_ALLOWED_ORIGINS = [
    "http://localhost:4200",
]

REST_FRAMEWORK = {
    "DEFAULT_SCHEMA_CLASS": "drf_spectacular.openapi.AutoSchema",
    "DEFAULT_FILTER_BACKENDS": [
        "django_filters.rest_framework.DjangoFilterBackend",
        "rest_framework.filters.SearchFilter",
        "rest_framework.filters.OrderingFilter",
    ],
    "DEFAULT_PAGINATION_CLASS": "rest_framework.pagination.PageNumberPagination",
    "PAGE_SIZE": 20,
}

SPECTACULAR_SETTINGS = {
    "TITLE": "FPL API",
    "VERSION": "1.0.0",
}

ROOT_URLCONF = 'fpl.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': ['templates'],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.debug',
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
                'fpl.context_preprocessors.app_version',
            ],
        },
    },
]

WSGI_APPLICATION = 'fpl.wsgi.application'


DATABASES = {
    'default': {
        'ENGINE': 'django.db.backends.postgresql',
        'NAME': os.getenv('postgres_db', 'python_fpl'),
        'USER': os.getenv('postgres_user', 'fpl'),
        'PASSWORD': os.getenv('postgres_password', 'fpl'),
        'HOST': os.getenv('postgres_host', 'localhost'),  # Default to localhost for local development
        'PORT': os.getenv('postgres_port', '5432'),
        'OPTIONS': {
            'options': '-c timezone=Etc/UTC'
        }
    }
}

# Override settings if running in GitHub Actions
if os.getenv('GITHUB_ACTIONS'):
    DATABASES['default']['USER'] = os.getenv('POSTGRES_USER', 'postgres')
    DATABASES['default']['PASSWORD'] = os.getenv('POSTGRES_PASSWORD', 'password')
    DATABASES['default']['HOST'] = os.getenv('POSTGRES_HOST', 'localhost')
    DATABASES['default']['PORT'] = os.getenv('POSTGRES_PORT', '5432')
    DATABASES['default']['NAME'] = os.getenv('POSTGRES_DB', 'postgres')

# Password validation
# https://docs.djangoproject.com/en/3.2/ref/settings/#auth-password-validators

MIGRATION_MODULES = {
    'players': 'players.migrations',
    'manager': 'manager.migrations',
    'penalties': 'penalties.migrations',
    'common': 'common.migrations',
    'teams': 'teams.migrations',
    # Add other apps in the order they should be migrated
}

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]


# Internationalization
# https://docs.djangoproject.com/en/3.2/topics/i18n/

LANGUAGE_CODE = 'en-us'

TIME_ZONE = 'Etc/UTC'

USE_I18N = True

USE_L10N = True

USE_TZ = True

CSRF_COOKIE_SECURE = True

# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/3.2/howto/static-files/

STATIC_URL = '/fpl/static/'
STATICFILES_DIRS = (
    os.path.join(BASE_DIR, "fpl/static"),
)

# Default primary key field type
# https://docs.djangoproject.com/en/3.2/ref/settings/#default-auto-field

DEFAULT_AUTO_FIELD = 'django.db.models.BigAutoField'

LOGGING = {
    'version': 1,
    # The version number of our log
    'disable_existing_loggers': False,
    'formatters': {
        'main_formatter': {
            'format': '(%(asctime)s.%(msecs)03d; %(filename)s): %(message)s ',
            'datefmt': "%Y-%m-%d %H:%M:%S",
        },
    },
    'handlers': {
        'console': {
            'class': 'logging.StreamHandler',
            'formatter': 'main_formatter',
        },
        'file': {
            'class': 'logging.handlers.TimedRotatingFileHandler',
            'filename': 'fpl_app.log',
            'formatter': 'main_formatter',
            'level': 'INFO',
            'encoding': 'utf-8',
            'when': 'D',  # Rotate daily
            'interval': 1,  # Rotate every day
            'backupCount': 7,  # Keep the last 7 days of logs
        },
    },
    'loggers': {
        '': {
            'handlers': ['console', 'file'],
            'level': 'INFO',
            'propagate': True,
        },
    },
    'filters': {
        'require_debug_true': {
            '()': 'django.utils.log.RequireDebugTrue',
        }
    },
    # 'handlers': {
    #     'console': {
    #         'level': 'DEBUG',
    #         'filters': ['require_debug_true'],
    #         'class': 'logging.StreamHandler',
    #     }
    # },
    # 'loggers': {
    #     'django.db.backends': {
    #         'level': 'DEBUG',
    #         'handlers': ['console'],
    #     }
    # }
}
