# Generated by Django 5.1.5 on 2025-01-25 18:55

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('common', '0002_initial'),
        ('players', '0001_initial'),
        ('teams', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Penalty',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('venue', models.CharField(choices=[('HOME', 'Home'), ('AWAY', 'Away')], default='HOME', max_length=4)),
                ('result', models.CharField(choices=[('SCORED', 'Scored'), ('MISSED', 'Missed'), ('SAVED', 'Saved')], default='SCORED', max_length=6)),
                ('var_awarded', models.BooleanField(default=False)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
                ('gameweek', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='common.event')),
                ('goalkeeper', models.ForeignKey(limit_choices_to={'player_type': 1}, on_delete=django.db.models.deletion.CASCADE, related_name='player_goalkeeper', to='players.player')),
                ('taker', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='player_taker', to='players.player')),
                ('team', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='teams.team')),
            ],
            options={
                'constraints': [models.UniqueConstraint(fields=('id',), name='unique_penalty')],
            },
        ),
    ]
