# Generated by Django 5.1.5 on 2025-01-25 18:55

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Team',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('strength_defence_away', models.IntegerField(null=True)),
                ('code', models.IntegerField(null=True)),
                ('strength', models.IntegerField(null=True)),
                ('unavailable', models.BooleanField(default=False, null=True)),
                ('strength_overall_away', models.IntegerField(null=True)),
                ('draw', models.IntegerField(null=True)),
                ('team_division', models.IntegerField(blank=True, null=True)),
                ('played', models.IntegerField(null=True)),
                ('pulse_id', models.IntegerField(null=True)),
                ('strength_attack_away', models.IntegerField(null=True)),
                ('points', models.IntegerField(null=True)),
                ('loss', models.IntegerField(null=True)),
                ('strength_defence_home', models.IntegerField(null=True)),
                ('form', models.IntegerField(blank=True, null=True)),
                ('strength_attack_home', models.IntegerField(null=True)),
                ('strength_overall_home', models.IntegerField(null=True)),
                ('name', models.CharField(max_length=30)),
                ('short_name', models.CharField(max_length=3)),
                ('position', models.IntegerField(null=True)),
                ('win', models.IntegerField(null=True)),
                ('last_updated', models.DateTimeField(auto_now=True)),
            ],
            options={
                'constraints': [models.UniqueConstraint(fields=('id', 'pulse_id', 'name'), name='unique_team')],
            },
        ),
        migrations.CreateModel(
            name='TeamPreviousPosition',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('season', models.IntegerField(null=True)),
                ('team', models.IntegerField(null=True)),
                ('position', models.IntegerField(null=True)),
                ('last_updated', models.DateTimeField(auto_now=True)),
                ('this_team', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='teams.team')),
            ],
            options={
                'constraints': [models.UniqueConstraint(fields=('season', 'team'), name='unique_team_previous_position')],
            },
        ),
    ]
